### ISSUE TITLE
Thieving export and missing dummy lines

### ISSUE THREAD

**Issue by karlsonrwa** [juulsA/exportJson#10]
Hello again!

I was testing your script and found out that it does not export thieving groups. I assume that you know that in Allegro thieving is a via with some padstack shape without drill. Is it possible to add thieving export? On some boards such things cover lots of board area.

Thanks for your work!

**Comment by juulsA** [comment]
Hi, 
I have to admit that I'm not quite sure what you mean ... do you mean something like a hatched shape? If you could provide an example (.brd), it would be much easier for me to figure out why the export is not working, thanks!

**Comment by karlsonrwa** [comment]
[AD-FMComms3_revA_thieving_and_text.zip](https://github.com/juulsA/exportJson/files/13226160/AD-FMComms3_revA_thieving_and_text.zip)

Here it is. I just made thieving and text one near another. The whole area looks empty after export.

![image](https://github.com/juulsA/exportJson/assets/2000739/f2b183dc-7190-4eb5-a323-795462e90ed3)

It should look like this.

![image](https://github.com/juulsA/exportJson/assets/2000739/6efb72dd-ade9-48b4-b323-014c7ad9dc78)

**Comment by juulsA** [comment]
Just as a hint: if you use a text element within allegro, the text should already be included in the output, but if you create a text from lines, this should work as well ... I have to look into that and I hope I can present you a working solution soon!

**Comment by juulsA** [comment]
In my latest commit the thieving structures should be added to the export ... except if circles are used ... there is still some work to do! Maybe you could check, if this is working for you as well.

**Comment by karlsonrwa** [comment]
Hex thieving works fine! Thank you very much!

**Comment by juulsA** [comment]
Dummy line segments are now also included in the export.

**Comment by juulsA** [comment]
Yes, I used the board [modified by you](https://github.com/juulsA/exportJson/issues/10#issuecomment-1788770243). 
I tested it again and it still works ... [AD-FMComms3_revA_thieving_and_text.zip](https://github.com/juulsA/exportJson/files/13298594/AD-FMComms3_revA_thieving_and_text.zip). Do you get an error?

**Comment by juulsA** [comment]
Yes, I did the export with your [board](https://github.com/juulsA/exportJson/issues/10#issuecomment-1788770243) ... see the attached [file](https://github.com/juulsA/exportJson/files/13298645/ibom.zip). Do you get an error?

**Comment by karlsonrwa** [comment]
From some point in time export of text failed again.
I asked Claude to help, he wrote this:

# Copper not on a net is omitted, and copper circles break JSON schema validation (with fixes)

Two related bugs in `exportJson.il`, each with a fix. They are independent, but the second one only becomes visible once the first is fixed.

## Environment

- Allegro PCB Editor / OrCAD — *(please fill in your version)*
- `exportJson` — *(commit / date)*
- InteractiveHtmlBom generic JSON parser (`genericjson.py`, schema `genericjsonpcbdata_v1.schema`)

---

## Issue 1 — copper that is not on a net is not exported

### Symptom

Etch that is not assigned to a net (editor tooltip: `line net name: not on a net`) is missing from the exported JSON, while on-net copper is exported correctly.

### Root cause

On-net copper is collected in `addCopper` by walking the database directly (`dsn->nets -> branches -> children`), which does **not** depend on layer visibility. No-net copper is collected separately in `addNoNetCopper`, which instead uses the selection mechanism:

```lisp
axlClearSelSet()
axlSetFindFilter(?enabled '("noall" "lines") ?onButtons '("lines"))
axlAddSelectAll()
lines = axlGetSelSet()
```

`axlAddSelectAll()` only selects objects that are currently **visible**. `addCopper` runs right after `addSymbols`, which repeatedly calls `axlVisibleDesign(nil)` and turns on individual documentation layers without restoring the etch layers. `addNoNetCopper` never makes its own target layer visible, so at that point the etch subclasses are hidden, `axlAddSelectAll()` returns an empty set, and all no-net copper is silently skipped.

This is why on-net copper (DB walk) and thieving (DB walk of `dsn->groups`) export fine, while no-net copper — the only part that relies on `axlAddSelectAll` — is the one that goes missing.

### Fix

Make the target etch layer visible before selecting, at the top of `addNoNetCopper`:

```lisp
procedure( addNoNetCopper( layer )
    let( ( ( tracks 'unbound ) lines line segments segment elem )
        axlVisibleDesign( nil )      ; <-- added
        axlVisibleLayer( layer t )   ; <-- added
        axlClearSelSet()
        axlSetFindFilter(?enabled '("noall" "lines") ?onButtons '("lines"))
        axlAddSelectAll()
        lines = axlGetSelSet()
        ...
```

`layer` arrives as `"ETCH/TOP"` / `"ETCH/BOTTOM"` / etc., which `axlVisibleLayer` accepts directly. The top-level `exportJson` already saves and restores the visibility state (`axlVisibleGet` / `axlVisibleSet`), so this leaves no lasting side effect.

**Optional optimization:** `addNoNetCopper` is called once per etch layer, so this toggles visibility (and triggers a redraw) N times. If preferred, the visibility setup can be hoisted into `addCopper` once, before the per-layer loop, to avoid the repeated redraws.

---

## Issue 2 — copper circles fail JSON schema validation

### Symptom

After Issue 1 is fixed, generation aborts with a schema error:

```
ERROR File ...\kup.json does not comply with json schema.
{'type': 'circle', 'start': [9.1315, -20.925], 'radius': 0.26, 'width': 0.2} is not valid under any of the given schemas
```

### Root cause

In the generic JSON schema, a `tracks` entry (`Track`) is a `oneOf`:

- segment: `{ start, end, width, [net] }`
- arc: `{ center, startangle, endangle, radius, width, [net] }`

Both have `additionalProperties: false`, so any object carrying a `type` field is invalid, and there is no "circle" form for tracks at all. `{ "type": "circle", ... }` is a `DrawingCircle`, which is only valid inside drawing layers (edges / silkscreen / fabrication).

`parseSegment` routes every full-circle arc to `addCircle`, which always emits a `DrawingCircle` regardless of context. On copper this produces an invalid track object. It was harmless only because no-net copper — where these circles occur — was never exported (Issue 1). Once Issue 1 is fixed, the first circular copper element breaks schema validation.

`addArc` already emits the correct track form for etch (`{ net, center, radius, startangle, endangle, width }`) and already contains explicit handling to represent a full circle as a 360° arc.

### Fix

In `parseSegment`, use `addCircle` only for drawing layers; on copper, route circles through `addArc`:

```lisp
            (
                "arc"
                ; circle-drawing is only valid on drawing layers;
                ; on copper (isEtch) a full circle must be a 360-degree arc-track
                if( segment->isCircle && isEtch == nil then
                    element = addCircle( segment width )
                else
                    element = addArc( segment width isEtch netName )
                )
            )
```

Drawing-layer circles (`isEtch == nil`) still go to `addCircle` and remain valid `DrawingCircle` objects; all copper circles (`isEtch = t`, in both `addNoNetCopper` and the main net walk) now become valid arc-tracks with a `net` field. This also fixes on-net copper circles, which would otherwise hit the exact same bug.

---

## Note on the interaction

The two issues are independent bugs, but they chain: Issue 2 stays latent until Issue 1 is fixed and copper without a net actually starts flowing into the `tracks` array.

---

*Diagnosis and both patches were prepared with the help of Claude (Anthropic's AI assistant), based on a read-through of `exportJson.il`, the InteractiveHtmlBom `genericjson.py` parser, and `genericjsonpcbdata_v1.schema`.*

With this two changes everything now works as expected. Please review if possible and modify your script if everything above is correct. And again thank you for your work!

**Comment by juulsA** [comment]
Thanks, for reporting these issues and for your suggested solutions. I have to look into this in more detail, which might take a while.

**Comment by juulsA** [comment]
The solution for the first issue ist correct and I have already added it to the code. I also run in the same problem as you mentioned in issue 2, but the solution does not work for me ... I think it is probably a little more complex, but I need to do a few more tests.

**Comment by juulsA** [comment]
Please take a look at my latest commit to see if it works for you as well.
