### ISSUE TITLE
Dummy net lines are absent

### ISSUE THREAD

**Issue by karlsonrwa** [juulsA/exportJson#11]
And again thank you very much for your script!

There is another glitch I found I think.

Shapes with "dummy nets" from etch are exported but lines are not. Is it possible to add them to export? I have some text made with lines of dummy net, it would be great to have it exported to graphics.

**Comment by karlsonrwa** [comment]
Please see file attached to this [message](https://github.com/juulsA/exportJson/issues/10#issuecomment-1788770243).

**Comment by juulsA** [comment]
Further progress is discussed in this [issue](https://github.com/juulsA/exportJson/issues/10).
