### ISSUE TITLE
> Sry for my late response ... I never had the chance to check that, so this was an approach for users using older files, but I think you're right, the mapping should not be dependent of the version... it's on my list, thanks!

### ISSUE THREAD

**Issue by Jinying-Tang** [juulsA/exportJson#15]
> Sry for my late response ... I never had the chance to check that, so this was an approach for users using older files, but I think you're right, the mapping should not be dependent of the version... it's on my list, thanks!

Thank you for your update. When converting to ibom, I have another issue: for lower versions of outline and cutout, if they are drawn using line segments or arcs (not shape types), these elements do not appear in the exported ibom.

_Originally posted by @Jinying-Tang in https://github.com/juulsA/exportJson/issues/14#issuecomment-2173626115_

**Comment by juulsA** [comment]
Can you share the .brd-files?

**Comment by Jinying-Tang** [comment]
> Can you share the .brd-files?

here is the boad design on allegro 17.2,  and the outline  is  include with segment and arcs
[Uploading demo.zip…]()

**Comment by Jinying-Tang** [comment]
> Please check the newest commit.

Now it can work perfectly.
Thank you for your help.

**Comment by juulsA** [comment]
Thank you for bug reporting!
