### ISSUE TITLE
Allegro PCB Designer board file json export - extra fields

### ISSUE THREAD

**Issue by blackbile71** [juulsA/exportJson#16]
Hello,

we tried your script which is working though we could not add extra fields to the .json file for example "Part number", is it possible?

You show a AD-FMComms3_revA.BRD file, from this we could export .json file which contain extra fields like: 

			"extra_fields": {
				"VALUE": "LNJ308G8TRA (green)",
				"TOL": "N/A",
				"SCH_MODIFIED_PART": "TRUE",
				"PART_NAME": "DIOLED",
				"PARENT_PPT_PART": "DIOLED_SM-LNJ308G8TRA (GREEN),4V,N/A,E006239,LED0603",
				"PARENT_PPT": "DIOLED",
				"PARENT_PART_TYPE": "DIOLED_SM"

But if we try using your script on our .brd file than the .json file doesn't contain any extra fields only 

				"VALUE": "2.6 mm furat",
				"PART_NAME": "PAD"

Could you give us some help what we have to change on export or Allegro netlist generation or something like another file?
Or maybe the problem is that we have exactly OrCAD PCB Designer Professional?

Thank you.

**Comment by juulsA** [comment]
Hi, 
the extra fields contain values assigned to a part. If the .json file does not contains any other values, the part has no user assigned values. If you use "Show Element" and select "Comps" in your find filter in allegro you can see under "Properties attached to component definition" all properties, which are exported. Otherwise I have to look into that.

**Comment by blackbile71** [comment]
Thank you for your asnwer! I saw what you asked and unfortunatelly I see this (some detail of one part):

...
 Attached text:
   class      = REF DES
   subclass   = SILKSCREEN_TOP
   value      = CS1

  Attached text:
   class      = COMPONENT VALUE
   subclass   = ASSEMBLY_TOP
   value      = 1473005-1

  Properties attached to symbol definition
    LIBRARY_PATH      = V:/Orcad/OrCAD_Footprint_Library/dev/1473005k_
                        tx6.psm


  -------Component Instance CS1-------

  Component Class:      IC
  Device Type:          TX6DL_1473005K_TX6_1473005-1
    Value:              1473005-1

  Function(s):
    Designator: F257
    Type:       TX6DL_1473005K_TX6_1473005-1
    Pin(s):     24, 20, 16, 17, 8...

  **Properties attached to component definition**
    VALUE             = 1473005-1

  Pin IO Information:
    Pin     Type      SigNoise Model          Net
    ---     ----      --------------          ---
    1       POWER                             N19590338
    2       POWER                             N19590338

...

So I look over what could I do to be more properties be there... do you have any hints?

**Comment by juulsA** [comment]
The properties must be defined in your component definition. If there are no more properties, they do not exist. I'm not an expert, but in my case I have a database containing the components with properties and in my schematic editor (OrCad) I can decide, which property is transferred to the pcb design. I'm not sure, if there is a way to manually add properties to a component...

**Comment by blackbile71** [comment]
Yes, meanwhile I figured out, in our database there are not other properties... I edited one part in CIS, added PART NUMBER property, wrote a string there and your script used it and it appears in the InteractiveHtmlBom (https://github.com/openscopeproject/InteractiveHtmlBom) script output.
Thank you.
