### ISSUE TITLE
exportJson error:can't handle (nil - 0.0)

### ISSUE THREAD

**Issue by yzx0708** [juulsA/exportJson#3]
Hi:
I want to convert an allegro .brd file to json after converting to ibom, but I get the following error:
Command > exportJson
W- *WARNING* No variant.lst found, exporting entire design ... 
CDS version: 16.600000
E- *Error* difference: can't handle (nil - 0.0)
Command > exportJson( ?excludeDNP t )
E- Command not found: exportJson( ?excludeDNP t )
I am not skilled in allegro, please advise how to solve this error, thank you!

**Comment by juulsA** [comment]
Hi,
this happens when allegro tries to access a property or something like this, that does not exist ... it would be the best, if you could share your design, so I can look into it. But please be patient, I can't look into it right away.

Moreover you're passing the `?excludeDNP` argument, but there's no variant.lst present. Please create the variant.lst or just execute `exportJson()`, maybe this already solves your problem.

**Comment by juulsA** [comment]
You are using the command line, which is fine, if you are only using `exportJson`, but if you want to pass arguments to that function you have to do that in the skill environment. That means, you have to type ` set telskill` to your command line first and a new window will open. In this window you can use the function with arguments. 

Anyway, only using exportJson won't solve your problem, so I will need your design ...

**Comment by yzx0708** [comment]
How did I give you my design files,email?

**Comment by juulsA** [comment]
Sorry for my late response ... you can attach your board file directly to this issue by dragging and dropping or please wait until I added some debug messages, so we can figure out, what the problem is. I think I'll get this done by tomorrow.

**Comment by yzx0708** [comment]
I'd better wait for you to add some debugging messages, thank you!

**Comment by yzx0708** [comment]
![err](https://github.com/juulsA/exportJson/assets/107865117/3e678d6f-b69f-4342-a611-c846f51e1ee6)
I passed through the exportJson.Il file added warn information, found that the error appeared in this position in the screenshot

**Comment by juulsA** [comment]
Ok, then I assume, that `outline->segments` is `nil`. Did you draw your board outline on the `Board Geometry/Outline` layer?

**Comment by yzx0708** [comment]
![outl](https://github.com/juulsA/exportJson/assets/107865117/2c7ea300-4aa6-41ab-85ba-6de4b055b3fd)
I drew the outline, which is a .bsm file.

**Comment by juulsA** [comment]
I'm not sure, what you mean with 

> " ... which is a .bsm file." 

But can you only apply "Shapes" to the find filter and try to select the board outline? If that doesn't work, that might even be our problem. Maybe there is no shape but just lines ...

**Comment by yzx0708** [comment]
> I'm not sure, what you mean with
> 
> > " ... which is a .bsm file."
> 
> But can you only apply "Shapes" to the find filter and try to select the board outline? If that doesn't work, that might even be our problem. Maybe there is no shape but just lines ...

Sorry, I'm not familiar with allegro, the description is wrong, this PCB outline is drawn with 4 ERTICAL LINE SEGMENT

**Comment by juulsA** [comment]
The board outline has to be a shape, otherwise the code is not working. So please draw a polygon instead of the individual lines. Or, just for testing, draw a rectangle and execute the code, then we know, that this is the reason, why the code is not working.

**Comment by yzx0708** [comment]
> The board outline has to be a shape, otherwise the code is not working. So please draw a polygon instead of the individual lines. Or, just for testing, draw a rectangle and execute the code, then we know, that this is the reason, why the code is not working.

I drew a rectangle on the outline and the conversion was successful, thank you very much.
