### ISSUE TITLE
Can I do this using command prompt

### ISSUE THREAD

**Issue by ankithjv** [juulsA/exportJson#5]
Is there anyway I could run a command on windows command prompt to export the json? The export to html in one step code you had. Where do I put that?

**Comment by ankithjv** [comment]
Do you know where I would code the automation? Can I use python and windows
command line?

**Comment by juulsA** [comment]
Maybe there is a way using python and the command line, but I do not know how this could be done. I would use skill, because the export has to be done from the allegro editor anyway.

**Comment by ankithjv** [comment]
Hey, is there anyway I can extract the pins associated with each component?

**Comment by ankithjv** [comment]
Thanks, Now I want the pin number of these associated pins. Is there a way to add this information to the json and still allow the json to work for the interactiveHTMLBom?

**Comment by ankithjv** [comment]
hi, I appreciate the help btw. So i am using the pinNumber property and it fills in some of the pins as empty strings whihc is causing a parsin error in the jsons. Im guessing its because they dont have pin numbers. How would I fix this so even if there is no pinNumber I wont get a parsing issue in the json?

**Comment by juulsA** [comment]
you could or you should check if the `pinNumber` is not `nil` and set a default, if the `pinNumber` has no value. 
This can be done by:

````
if( pinNumber then
   ; set the pinNumber
else 
  ; set a default value
)
````

I hope this helps ...

**Comment by ankithjv** [comment]
okay so the issue is actually with the type cast of pinNumber. How do I insert the pinNumber value so it gets parsed? I guess unless it is a number it isnt working. For example if a pin is G14 Im getting the error

**Comment by juulsA** [comment]
Try this 'sprintf( nil "%L pinNumber )'

**Comment by ankithjv** [comment]
where should I insert this? When I tried to replace just where I referenced "pinNumber" with that line I got  this error 
function figureToSvgPath redefined
E- 
E-                 pad = strcat( pad ",\n"
E-                                       ^
E-                     svgpath
E- ^^^^^^^^^^^^^^^^^^^^^^^^^^^
E-                 )
E- ^^^^^^^^^^^^^^^^^
E-             )
E- ^^^^^^^^^^^^^
E- 
E- 
E- 
E- 
E-             ; if present, add the drill information
E- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E-             when( boundp( 'drill )
E- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E-                 ;build pad
E- ^^^^^^^^^^^^^^^^^^^^^^^^^^
E-                 pad = strcat( pad ",\n" drill )
E- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E- SYNTAX ERROR found at line 1207 column 39 of file exportJson.il
E- *Error* lineread/read: syntax error encountered in input
E- *Error* load: error while loading file - "exportJson.il" at line 1216
ERROR

**Comment by ankithjv** [comment]
wait I figured it out,    pad = strcat(                
                "\"layers\": " layers ",\n"
                "\"pos\": " pos ",\n"
                "\"size\": " size ",\n"
                "\"angle\": " angle ",\n"
                "\"shape\": " shape ",\n"
                "\"net\": " net ",\n"
                "\"type\": " type ",\n"
		"\"pin\": " pinNumber 
            )
this is how I added pin number, now the issue is that the actual pin vlaue number doesnt come out in quotes like the rest do. How do I make the value come in quotes. Fro example: 
						"layers": ["B"],
						"pos": [ 2430.940000, 25.580000],
						"size": [ 38.000000, 38.000000],
						"angle": 0.000000,
						"shape": "circle",
						"net": "L/G",
						"type": "smd",
						"pin": G16

this is how it come out but it should be "pin": "G16"

**Comment by ankithjv** [comment]
pad = strcat(                
                "\"layers\": " layers ",\n"
                "\"pos\": " pos ",\n"
                "\"size\": " size ",\n"
                "\"angle\": " angle ",\n"
                "\"shape\": " shape ",\n"
                "\"net\": " net ",\n"
                "\"type\": " type ",\n"
		"\"pin\": " pinNumber
            )
how would I change it here sorry

**Comment by juulsA** [comment]
Github removes the important thing ...

Within a string a `"` needs to be escaped by a `\`. So the solution is

````
"\"pin\": \"" pinNumber "\"" 
````

**Comment by ankithjv** [comment]
![image](https://github.com/juulsA/exportJson/assets/51538031/b33a5124-3573-4b07-ae27-0596e69a8bef)
It is still coming out like this so sad

**Comment by ankithjv** [comment]
is there anyway for me to define pinNumber or pin->number as a string?

**Comment by juulsA** [comment]
It is already a string, since you are using the strcat ... there is something wrong in your code ... please have a look at this [line](https://github.com/juulsA/exportJson/blob/b08bc271921e7027785182d4e997c3160dc2713b/exportJson.il#L119). You have to do it the same way, except, that you have to use your variable `pinNumber` instead of `circle`.

**Comment by ankithjv** [comment]
ahhhh yes it finally worked thank you so much for helping me so much.
