### ISSUE TITLE
Opportunity to convert several Outline shapes to json for Allegro 16.6

### ISSUE THREAD

**Issue by Kartohen** [juulsA/exportJson#6]
I've added opportuniti to convert several Outline shapes to json. Mybe it would be useful in case if we have Outline shapes inside of main Outline: 
![image](https://github.com/juulsA/exportJson/assets/131638318/54f89987-e860-405e-8eef-307d13b67e69)

**Comment by juulsA** [comment]
Sorry for my late reply ... and thanks for the hint! In allegro 17.4 there is an extra layer named `cutouts` and I remember, in all previous versions everything is drawn at the board outline layer ?!

**Comment by Kartohen** [comment]
No, we don't have layer `cutouts` and it's the main problem with this version of allegro:
![image](https://github.com/juulsA/exportJson/assets/131638318/7c5b2e4b-7bd6-4518-a199-071fc0d0d20f)

**Comment by juulsA** [comment]
I'll add support for that, but it will take some time ... I'm out of office at the moment.

**Comment by juulsA** [comment]
I'm sorry it took me so long to implement the support for 16.6, but I made a few attempts that always ended with the script crashing ... maybe you could check, if the script now works for 16.6?

**Comment by Jacky-huangfc** [comment]
W- *WARNING* No variant.lst found, exporting entire design ... 
CDS version: 16.600000
E- *Error* No board geometry found ...
Command >

**Comment by juulsA** [comment]
Can you share the board file?
