### ISSUE TITLE
*Error* difference: can't handle (nil-0.0)

### ISSUE THREAD

**Issue by DaLaoHei1986** [juulsA/exportJson#7]
Hello, I have the following problem with the software version 17.4, how should I solve it? *Error* difference: can't handle (nil-0.0)

![图片](https://github.com/juulsA/exportJson/assets/58840112/b377807a-cfe1-4cba-b1f2-318f6ff64220)

**Comment by juulsA** [comment]
Hi, 
have updated your git-repo to the latest version? Do you have a pcb outline on the "BOARD GEOMETRY/DESIGN_OUTLINE" layer?

**Comment by DaLaoHei1986** [comment]
> 你好 是否已将您的 git 存储库更新到最新版本？您在“电路板几何形状/DESIGN_OUTLINE”层上有PCB轮廓吗？
Yes, I drew a rectangle in the OUTLINE layer to test and found that it still didn't work
![图片](https://github.com/juulsA/exportJson/assets/58840112/98e887cb-831f-4b78-8254-f79fa85e22cf)

**Comment by DaLaoHei1986** [comment]
![图片](https://github.com/juulsA/exportJson/assets/58840112/ceac872d-cd10-4859-ab63-6d5fe1dd6c34)
我单独创建了一个PCB文件，仅仅放置了一个元器件，也不行，好难！快哭了

**Comment by juulsA** [comment]
The pcb outline must be drawn on the Board Geometry/Design_Outline layer, not on any other ...

**Comment by DaLaoHei1986** [comment]
> PCB 轮廓必须绘制在 Board Geometry/Design_Outline 层上，而不是任何其他...

![图片](https://github.com/juulsA/exportJson/assets/58840112/8a61558c-f2df-4223-ae33-138d35c1f438)

Got it! Thank you very much!!!
