### ISSUE TITLE
Hello! Can other parameters be added to the BOM? For example, self-defined parameters such as' VOLTAGE 'or' Tolerance '

### ISSUE THREAD

**Issue by DaLaoHei1986** [juulsA/exportJson#8]
Hello! Can other parameters be added to the BOM? For example, self-defined parameters such as' VOLTAGE 'or' Tolerance '

![图片](https://github.com/juulsA/exportJson/assets/58840112/d1bdb0c2-7de6-4fe1-9119-b64db81c512d)

**Comment by DaLaoHei1986** [comment]
![图片](https://github.com/juulsA/exportJson/assets/58840112/c5623b6b-c62d-4dbc-935c-af6926fd880e)

**Comment by DaLaoHei1986** [comment]
> 所有自定义属性都包含在 json 文件中。如果要在标记位置添加属性，则需要自己编写代码。

Thank you for your reply. I will try it now and hope to modify it

**Comment by xiehuan614** [comment]
@DaLaoHei1986 Was the addition successful? Could you tell me how to add it? On which files?

**Comment by mpikmwm** [comment]
For me it worked, after I followed this: [https://www.parallel-systems.co.uk/wp-content/uploads/2022/05/User_defined_properties.pdf](https://www.parallel-systems.co.uk/wp-content/uploads/2022/05/User_defined_properties.pdf)

And added the extra fields to the config.json like:
```
    "settings": {
        "exportInnerLayer": false,
        "renderViaHoles": false,
        "textAsSvgPaths": true,
        "excludeDNP": false,
        "pcbLinewidth": "design",
        "fabricationLayerLinewidth": "design",
        "silkscreenLayerLinewidth": "design",
        "marginTop": 0.0,
        "marginRight": 0.0,
        "marginBottom": 0.0,
        "marginLeft": 0.0,
		"extra_fields": [
			"MANUFACTURER",
			"MANUFACTURER_NUM"
		]
    }
}
```

and to the args of the script ` generate_interactive_bom --extra-fields MANUFACTURER,MANUFACTURER_NUM ...`

**Comment by xiehuan614** [comment]
已收到你的邮件！

**Comment by juulsA** [comment]
What works ist this: 

> For me it worked, after I followed this: https://community.cadence.com/cadence_technology_forums/pcb-design/f/allegro-x-capture-cis/47698/import-user-defined-property-from-capture-schematic-to-pcb-editor-layout

But don't add the extra fields to the `config.json`. The `extra_fields` there have no effect. The `config.json` has only the described parameters and no others can be added.
